### ISSUE TITLE
[BUG] - FATAL: The app has crashed

### ISSUE THREAD

**Issue by Pascal66** [m4dm4rtig4n/enedisgateway2mqtt#101]
**Description du bug**
Après un import correct (SUCCESS)
```
2022-01-11 10:36:56.116274 - INFO  : ------------------------------------------------------------------------------------
2022-01-11 10:36:56.116496 - INFO  :                    SUCCESS : Consumption detail imported
2022-01-11 10:36:56.116565 - INFO  : ------------------------------------------------------------------------------------
(Suite à la fin)
```
**Configuration**
```
cycle: 3600
debug: true
enedis_gateway:
  24xxxxxxxxxxxx:
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1558
    consumption_price_hc: 0.1360
    consumption_price_hp: 0.1821
    offpeak_hours: 21h56-05h56
    plan: BASE
    production: true
    production_detail: true
    refresh_addresses: false
    refresh_contract: false
    token: 4Rxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
mqtt:
  client_id: enedis_gateway
  host: core-mosquitto
  password: 'passwd'
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
  username: 'user'
wipe_cache: false

```

**Type d'installation**
HassIO 

**Version : Current version: 0.7.8-dev**

***Full log***
```
2022-01-11 10:36:56.116274 - INFO  : ------------------------------------------------------------------------------------
2022-01-11 10:36:56.116496 - INFO  :                    SUCCESS : Consumption detail imported
2022-01-11 10:36:56.116565 - INFO  : ------------------------------------------------------------------------------------
2022-01-11 10:36:56.116638 - INFO  : ####################################################################################
2022-01-11 10:36:56.116734 - INFO  : Home Assistant auto-discovery (Consumption Detail) :
2022-01-11 10:36:56.117404 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hc/config => {"name": "enedisgateway_24253834992458_consumption_detail_this_month_hc", "uniq_id": "enedisgateway.24253834992458_consumption_detail_this_month_hc", "stat_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hc/state", "json_attr_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hc/attributes", "device": {"identifiers": ["linky_24253834992458"], "name": "Linky 24253834992458", "model": "Linky", "manufacturer": "Enedis"}, "unit_of_meas": "kWh", "device_class": "energy", "state_class": "total_increasing"}
2022-01-11 10:36:56.117778 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hc/attributes => {"ratio": 7.81, "W": 67742, "measure_hc_euro": 4.6064560000000006}
2022-01-11 10:36:56.117969 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hc/state => 33.871
2022-01-11 10:36:56.118444 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hp/config => {"name": "enedisgateway_24253834992458_consumption_detail_this_month_hp", "uniq_id": "enedisgateway.24253834992458_consumption_detail_this_month_hp", "stat_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hp/state", "json_attr_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hp/attributes", "device": {"identifiers": ["linky_24253834992458"], "name": "Linky 24253834992458", "model": "Linky", "manufacturer": "Enedis"}, "unit_of_meas": "kWh", "device_class": "energy", "state_class": "total_increasing"}
2022-01-11 10:36:56.118716 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hp/attributes => {"ratio": 69.71, "W": 597198, "measure_hp_euro": 54.3748779}
2022-01-11 10:36:56.118966 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_hp/state => 298.599
2022-01-11 10:36:56.123542 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_base/config => {"name": "enedisgateway_24253834992458_consumption_detail_this_month_base", "uniq_id": "enedisgateway.24253834992458_consumption_detail_this_month_base", "stat_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_base/state", "json_attr_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_base/attributes", "device": {"identifiers": ["linky_24253834992458"], "name": "Linky 24253834992458", "model": "Linky", "manufacturer": "Enedis"}, "unit_of_meas": "kWh", "device_class": "energy", "state_class": "total_increasing"}
2022-01-11 10:36:56.124213 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_base/attributes => {"W": 867644, "measure_base_euro": 67.58946759999999}
2022-01-11 10:36:56.124445 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_base/state => 433.822
2022-01-11 10:36:56.125049 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_compare/config => {"name": "enedisgateway_24253834992458_consumption_detail_this_month_compare", "uniq_id": "enedisgateway.24253834992458_consumption_detail_this_month_compare", "stat_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_compare/state", "json_attr_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_compare/attributes", "device": {"identifiers": ["linky_24253834992458"], "name": "Linky 24253834992458", "model": "Linky", "manufacturer": "Enedis"}}
2022-01-11 10:36:56.125522 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_compare/attributes => {"best_plan_percent": "14.59"}
2022-01-11 10:36:56.125712 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_month_compare/state => HC/HP
2022-01-11 10:36:56.126961 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_year_compare/config => {"name": "enedisgateway_24253834992458_consumption_detail_this_year_compare", "uniq_id": "enedisgateway.24253834992458_consumption_detail_this_year_compare", "stat_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_year_compare/state", "json_attr_t": "homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_year_compare/attributes", "device": {"identifiers": ["linky_24253834992458"], "name": "Linky 24253834992458", "model": "Linky", "manufacturer": "Enedis"}}
2022-01-11 10:36:56.128116 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_year_compare/attributes => {"best_plan_percent": "14.59"}
2022-01-11 10:36:56.128479 - DEBUG :  MQTT Send : homeassistant/sensor/enedisgateway/24253834992458_consumption_detail_this_year_compare/state => HC/HP
2022-01-11 10:36:56.128563 - INFO  :  => HA Sensor updated
2022-01-11 10:36:56.128634 - INFO  : ####################################################################################
2022-01-11 10:36:56.128700 - INFO  : Get production :
2022-01-11 10:36:56.254412 - INFO  : Data is missing between 2021-01-11 / 2022-01-11
2022-01-11 10:36:56.254852 - INFO  :  => Load data from API
2022-01-11 10:36:56.256216 - DEBUG : call_number : 8 (max : 15)
2022-01-11 10:36:56.270783 - DEBUG : Call API : https://enedisgateway.tech/api
2022-01-11 10:36:56.271159 - DEBUG : Data : {"type": "daily_production", "usage_point_id": "24253834992458", "start": "2021-01-11", "end": "2022-01-11"}
'API Return :'
{'alert_user': True,
 'enedis_return': True,
 'support': 'https://discord.gg/DfVJZme',
 'tag': 'enedis_return_ko'}
2022-01-11 10:37:02.534748 - INFO  : =====> ERROR : Exception <======
2022-01-11 10:37:02.535129 - INFO  : 'meter_reading'
2022-01-11 10:37:02.535560 - INFO  : ==> tag => enedis_return_ko
2022-01-11 10:37:02.536248 - INFO  : ==> alert_user => True
2022-01-11 10:37:02.536322 - INFO  : ==> enedis_return => True
2022-01-11 10:37:02.536909 - INFO  : ==> support => https://discord.gg/DfVJZme
2022-01-11 10:37:02.539709 - DEBUG :  MQTT Send : enedis_gateway/24253834992458/production/current_year/error => 0
2022-01-11 10:37:02.540414 - DEBUG :  MQTT Send : enedis_gateway/24253834992458/production/current_year/dateBegin => 2021-01-11
2022-01-11 10:37:02.546286 - DEBUG :  MQTT Send : enedis_gateway/24253834992458/production/current_year/dateEnded => 2022-01-11
Traceback (most recent call last):
  File "/app/main.py", line 654, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 364, in run
    ha_discovery_production = day.getDaily(headers, cur, con, client, pdl, pdl_config, "production",
  File "/app/daily.py", line 48, in getDaily
    current_value = int(value["value"])
TypeError: string indices must be integers
[10:37:02] FATAL: The app has crashed. Are you sure you entered the correct config options?
```

**Comment by m4dm4rtig4n** [comment]
Hello à première vu c'est une indisponibilité des API Enedis.
Malheuresement je n'ai pas la main sur cette partie.

**Comment by Pascal66** [comment]
Salut, je vois plutôt l'erreur au niveau de l'api, qui concerne daily_production :
Il faut que j'essaye demain en enlevant la partie production
```
2022-01-11 10:36:56.254852 - INFO  :  => Load data from API
2022-01-11 10:36:56.256216 - DEBUG : call_number : 8 (max : 15)
2022-01-11 10:36:56.270783 - DEBUG : Call API : https://enedisgateway.tech/api
2022-01-11 10:36:56.271159 - DEBUG : Data : {"type": "daily_production", "usage_point_id": "24253834992458", "start": "2021-01-11", "end": "2022-01-11"}
'API Return :'
{'alert_user': True,
 'enedis_return': True,
 'support': 'https://discord.gg/DfVJZme',
 'tag': 'enedis_return_ko'}
2022-01-11 10:37:02.534748 - INFO  : =====> ERROR : Exception <======
```

**Comment by Pascal66** [comment]
Voilà, je confirme ce matin qu'après avoir mis `prodution` et `production_detail` sur false, même si je dépasse les 15 (c'est normal)
L'app ne crash plus

**Comment by Pascal66** [comment]
Etonnant. En fait crash de l'app quand même, une heure plus tard, sans raison
```
2022-01-12 10:39:31.967085 - INFO  :  => Sensor generated
2022-01-12 10:39:31.967893 - INFO  : ####################################################################################
2022-01-12 10:39:31.968340 - INFO  : IMPORT FINISH
2022-01-12 10:39:31.968529 - INFO  : ####################################################################################
Traceback (most recent call last):
  File "/app/main.py", line 654, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 243, in run
    f.logLine()
AttributeError: '_io.TextIOWrapper' object has no attribute 'logLine'
[11:39:32] FATAL: The app has crashed. Are you sure you entered the correct config options?
```

**Comment by m4dm4rtig4n** [comment]
Dans la 0.7.8, j'ai amélioré 2 3 truc au niveau de la remonter des logs afin que ce soit un peu plus clair.

**Comment by Pascal66** [comment]
> Dans la futur 0.7.8, j'ai amélioré 2 3 truc au niveau de la remonter des logs afin que ce soit un peu plus clair.

C'est bien la 0.7.8-dev que j'utilise depuis le début.

**Comment by m4dm4rtig4n** [comment]
Ouch je te déconseille de ne pas utiliser cette version en prod pour l'instant, elle est en cour de dev et très instable.
Et les dernières modification n'ont pas encore était push.

**Comment by Pascal66** [comment]
Ceci expliquerai cela 👍 Je vais essayer l'autre donc
