### ISSUE TITLE
[BUG] - TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by Ikari34** [m4dm4rtig4n/enedisgateway2mqtt#118]
**Description du bug**
Dépassement du nombre d'essais systématiquement (16/15). Carte My Enedis non mise à jour, affiche toujours les mêmes valeurs, effacement du fichier .db avant chaque essai. J'ai testé la commande de test curl après la demande de consentement : OK. 
fin du log en debug 
`                                        {'date': '2022-06-12 23:00:00',
                                         'interval_length': 'PT30M',
                                         'measure_type': 'B',
                                         'value': '602'},
                                        {'date': '2022-06-12 23:30:00',
                                         'interval_length': 'PT30M',
                                         'measure_type': 'B',
                                         'value': '560'},
                                        {'date': '2022-06-13 00:00:00',
                                         'interval_length': 'PT30M',
                                         'measure_type': 'B',
                                         'value': '552'}],
                   'quality': 'BRUT',
                   'reading_type': {'aggregate': 'average',
                                    'measurement_kind': 'power',
                                    'unit': 'W'},
                   'start': '2022-06-06',
                   'usage_point_id': 'xxxxxxxxxxxxxxxxxx'}}
2022-08-01 09:43:37.701015 - INFO  : Import data :
2022-08-01 09:43:37.972731 - INFO  :   => Import 336 entry
2022-08-01 09:43:37.974298 - INFO  : Load 2022-05-30 => 2022-06-06
2022-08-01 09:43:37.978194 - INFO  : Data is missing between 2022-05-30 / 2022-06-06
2022-08-01 09:43:37.978522 - INFO  :  => Load data from API
2022-08-01 09:43:37.979043 - DEBUG : call_number : 13 (max : 15)
2022-08-01 09:43:37.999784 - DEBUG : Call API : https://enedisgateway.tech/api
2022-08-01 09:43:37.999911 - DEBUG : Data : {"type": "consumption_load_curve", "usage_point_id": "xxxxxxxxxxxxxxxxxxx", "start": "2022-05-30", "end": "2022-06-06"}
'API Return :'
{'alert_user': True,
 'description': 'Quota Q3 reached. Call threshold allowed on -3:-23:-35',
 'enedis_return': True,
 'error_code': '429',
 'support': 'https://discord.gg/DfVJZme',
 'tag': 'enedis_return_ko'}
2022-08-01 09:43:41.604975 - ERROR : API return error beetween 2022-05-30 / 2022-06-06
2022-08-01 09:43:41.605066 - ERROR :  => Quota Q3 reached. Call threshold allowed on -3:-23:-35
2022-08-01 09:43:41.605494 - DEBUG :  MQTT Send : enedis_gateway/xxxxxxxxxxxxxxxx/consumption/detail/error => 1
2022-08-01 09:43:41.606010 - DEBUG :  MQTT Send : enedis_gateway/xxxxxxxxxxxxxxxxxx/consumption/detail/errorMsg/dateBegin => 2022-05-30
2022-08-01 09:43:41.606898 - DEBUG :  MQTT Send : enedis_gateway/xxxxxxxxxxxxxxxxxx/consumption/detail/errorMsg/dateEnded => 2022-06-06
2022-08-01 09:43:41.608248 - DEBUG :  MQTT Send : enedis_gateway/xxxxxxxxxxxxxxxxxx/consumption/detail/errorMsg/error_code => 429
Traceback (most recent call last):
  File "/app/main.py", line 656, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 328, in run
    ha_discovery_consumption = detail.getDetail(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/detail.py", line 131, in getDetail
    result[year][month]["measure_hp_euro"] = result[year][month]["measure_hp_wh"] / 1000 * price_hp
TypeError: can't multiply sequence by non-int of type 'float'
[09:43:41] FATAL: The app has crashed. Are you sure you entered the correct config options?`

**Configuration**
cycle: 3600
debug: true
enedis_gateway:
  xxxxxxxxxxxxxxxxxxxxxxxxxxx:
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0
    consumption_price_hc: 0,1470
    consumption_price_hp: 0,1841
    offpeak_hours: 3H00-8H00;12H30-15H30
    plan: HP/HC
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Type d'installation**
HAOS
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Interface utilisateur : 20220707.1 - latest

**Comment by Ikari34** [comment]
Désolé pour cette issue : réponse au pb de virgule dans les montants des HC/HP trouvée dans l'issue #114.
