### ISSUE TITLE
Invalid header value b'0.7.3\n'

### ISSUE THREAD

**Issue by Balooforever** [m4dm4rtig4n/enedisgateway2mqtt#55]
Bonjour,

Avec la nouvelle version (je n'avais pas fait la MAJ depuis un certain temps), le docker se lance puis s'arrête tout seul.

Je ne pense pas avoir mal configuré le fichier yaml, il me sort ceci : 
`Invalid header value b'0.7.3\n'
Traceback (most recent call last):
File "/app/daily.py", line 201, in dailyBeetwen
daily = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
File "/app/function.py", line 132, in apiRequest
retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
self.putheader(hdr, value)
File "/usr/local/lib/python3.9/http/client.py", line 1257, in putheader
raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'0.7.3\n'`

**Comment by m4dm4rtig4n** [comment]
Erreur de ma part je viens de relancer un rebuild de la 0.7.3.
Un "\n" c'était glissé au mauvais endroit :/

**Comment by m4dm4rtig4n** [comment]
la 0.7.3 est en ligne.
