### ISSUE TITLE
Erreur API Invalid header value b'0.7.3\n'

### ISSUE THREAD

**Issue by darthmamour** [m4dm4rtig4n/enedisgateway2mqtt#58]
2021-11-18 09:54:22.395555 - INFO  : Get Consumption :
2021-11-18 09:54:22.509878 - INFO  : Data is missing between 2021-04-14 / 2021-11-18
2021-11-18 09:54:22.510057 - INFO  :  => Load data from API
2021-11-18 09:54:23.075113 - INFO  : =====> ERROR : Exception <======
2021-11-18 09:54:23.075391 - INFO  : Invalid header value b'0.7.3\n'
Traceback (most recent call last):
  File "/app/daily.py", line 201, in dailyBeetwen
    daily = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 132, in apiRequest
    retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.9/http/client.py", line 1257, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'0.7.3\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 619, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 219, in run
    ha_discovery_consumption = day.getDaily(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/daily.py", line 34, in getDaily
    data = dailyBeetwen(headers, cur, con, url, pdl, mode, dateBegin, dateEnded, last_activation_date)
  File "/app/daily.py", line 337, in dailyBeetwen
    for error_key, error_msg in daily.items():
UnboundLocalError: local variable 'daily' referenced before assignment
[09:54:23] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by darthmamour** [comment]
Pardon, suite à arrêt et redemarage de l'application plus d'erreur...

**Comment by m4dm4rtig4n** [comment]
Yep bug dans la 0.7.3 (je l'ai rebuild plus tard), passe en 0.7.4 :)
