### ISSUE TITLE
[BUG] - Crash  du container toutes les minutes

### ISSUE THREAD

**Issue by B1n00** [m4dm4rtig4n/enedisgateway2mqtt#64]
**Describe the bug**
Le container redémarre toutes les minutes à cause d'une erreur de format sur le off_peak
```
enedisgateway2mqtt_1  | Traceback (most recent call last):
enedisgateway2mqtt_1  |   File "/app/main.py", line 619, in <module>
enedisgateway2mqtt_1  |     run(pdl, pdl_config)
enedisgateway2mqtt_1  |   File "/app/main.py", line 185, in run
enedisgateway2mqtt_1  |     contract = cont.getContract(headers, client, cur, con, pdl, pdl_config)
enedisgateway2mqtt_1  |   File "/app/contract.py", line 90, in getContract
enedisgateway2mqtt_1  |     offpeak_hours = pdl_config['offpeak_hours'].split(';')
enedisgateway2mqtt_1  | AttributeError: 'int' object has no attribute 'split'

```
**Configuration**
```
cycle: 3600
debug: false
enedis_gateway:
  xxxxxxxxxxxxxxxx:
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1228
    consumption_price_hc: 0.1160
    consumption_price_hp: 0.1621
    offpeak_hours: ''
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: true
    refresh_contract: true
    token: 'xxxxxxxxxxxxxxxxxxxxx'
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
mqtt:
  client_id: enedis_gateway
  host: 10.0.0.40
  password: 'xxxxxx'
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
  username: 'xxxxxx'
wipe_cache: false

```
**Installation type**
Docker
**Version : 0.7.6**

**Comment by m4dm4rtig4n** [comment]
Retire le offpeak_hours.
