### ISSUE TITLE
Probleme de connexion à InfluxDb depuis la dernière MAJ 0.7.7-dev-2

### ISSUE THREAD

**Issue by schumissimo63** [m4dm4rtig4n/enedisgateway2mqtt#71]
2021-11-22 12:12:58.525323 - INFO  : InfluxDB connect :
2021-11-22 12:12:58.551770 - INFO  :  => Connection success
2021-11-22 12:12:58.552419 - INFO  : Reset InfluxDB data
Traceback (most recent call last):
  File "/app/main.py", line 642, in <module>
    delete_api.delete(start, stop, '_measurement="enedisgateway_daily"', config['influxdb']['bucket'],
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/client/delete_api.py", line 35, in delete
    return self._service.post_delete(delete_predicate_request=predicate_request, bucket=bucket, org=org)
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/delete_service.py", line 58, in post_delete
    (data) = self.post_delete_with_http_info(delete_predicate_request, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/service/delete_service.py", line 142, in post_delete_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/api_client.py", line 341, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/api_client.py", line 171, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/api_client.py", line 386, in request
    return self.rest_client.POST(url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/rest.py", line 304, in POST
    return self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/influxdb_client/rest.py", line 254, in request
    raise ApiException(http_resp=r)
influxdb_client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': '1.8.10', 'Date': 'Mon, 22 Nov 2021 11:12:58 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
[12:12:58] FATAL: The app has crashed. Are you sure you entered the correct config options?

**Comment by m4dm4rtig4n** [comment]
Tu peut me donner ton config.yaml (anonymisé) stp.

**Comment by schumissimo63** [comment]
cycle: 3600
debug: false
enedis_gateway:
  XXXXXX:
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1787
    consumption_price_hc: 0.2113
    consumption_price_hp: 0.2432
    offpeak_hours: null
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: true
    refresh_contract: true
    token: XXXXXX
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
#influxdb:
#    host: 192.168.1.23
#    port: 8086
#    token: XXXXXX:XXXXXX
#    org: "_"
#    bucket: "linky/autogen"
mqtt:
  client_id: enedis_gateway
  host: XXXXXX
  password: 'XXXXXX'
  port: 1883
  prefix: enedis_gateway
  qos: 0
  retain: true
  username: 'XXXXXX'
wipe_cache: false

**Comment by m4dm4rtig4n** [comment]
J'ai retirer le reset dans le prochain build.

**Comment by schumissimo63** [comment]
Apres avoir réactivé les lignes d'influxdb et rebooté j'ai toujours le même message d'erreur.
