### ISSUE TITLE
[BUG] - Crash app 

### ISSUE THREAD

**Issue by aladin2000** [m4dm4rtig4n/enedisgateway2mqtt#75]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Crash de l'app en passant à la nouvell version sans modif du fichier config.yaml qui fonctionnait avant 

scripts/00-global_var.sh: executing
Timezone set from Etc/UTC to Europe/Paris
Custom user defined : :
**groupmod: group 'abc' does not exist
usermod: user 'abc' does not exis**t
scripts/00-global_var.sh: exiting 6
scripts/99-run.sh: executing
[19:02:57] INFO: Using config file found in /config/enedisgateway2mqtt/config.yaml
Config file is a valid yaml
creating symlink
....
2021-11-23 23:44:54.857068 - DEBUG : Data : {"type": "daily_consumption", "usage_point_id": "211......20", "start": "2020-11-23", "end": "2021-11-23"}
2021-11-23 23:44:55.132147 - INFO  : =====> ERROR : Exception <======
2021-11-23 23:44:55.132647 - INFO  : Invalid header value b'0.7.8-dev\n'
Traceback (most recent call last):
  File "/app/daily.py", line 206, in dailyBeetwen
    daily = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
  File "/app/function.py", line 145, in apiRequest
    retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.9/http/client.py", line 1257, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'0.7.8-dev\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/main.py", line 654, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 291, in run
    ha_discovery_consumption = day.getDaily(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/daily.py", line 39, in getDaily
    data = dailyBeetwen(headers, cur, con, url, pdl, mode, dateBegin, dateEnded, last_activation_date)
  File "/app/daily.py", line 342, in dailyBeetwen
    for error_key, error_msg in daily.items():
UnboundLocalError: local variable 'daily' referenced before assignment
**[23:44:55] FATAL: The app has crashed. Are you sure you entered the correct config options?**

**Configuration**
####################
####################
mqtt:
  host: 192.168.x.y# MANDATORY
  port: 1883
  username: "m---"
  password: "p----"
  prefix: enedis_gateway
  client_id: enedis_gateway
  retain: true
  qos: 0

####################
####################
home_assistant:
  discovery: false
  discovery_prefix: homeassistant
  card_myenedis: true

influxdb:
    host: 192.168.x.y
    port: 8086
    token: --hiden--
    org: "-"
    bucket: "linky/autogen"

####################
####################
enedis_gateway:
  21--hiden---0:
    token: ** hiden**    TZ: "Europe/Paris"
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.1556
    consumption_price_hc: 0.1763
    consumption_price_hp: 0.1321
    plan: BASE
    production: false
    production_detail: false

**Type d'installation**
HassIO 

**Version : X.X.X**
0.7.8-dev

**Comment by m4dm4rtig4n** [comment]
La 0.7.8-dev est en dev est encore instable.
Je vous déconseille de l'utiliser.

Cependant j'ai fix ce soucis hier soir, je ne sais pas quand l'addon HassIO va être mis à jour par contre.
