### ISSUE TITLE
[BUG] - Crash on JSONDecodeError

### ISSUE THREAD

**Issue by lesensei** [m4dm4rtig4n/enedisgateway2mqtt#87]
MERCI DE RESPECTER LES DIFFERENTS CHAMPS SINON JE CLOS L'ISSUE.

**Description du bug**
Lors du lancement, après la récupération des données d'historique, le conteneur finit par crasher:
```
enedis2mqtt    | 2021-12-17 00:37:01.623043 - INFO  : Import data :
enedis2mqtt    | 2021-12-17 00:37:02.645166 - INFO  :   => Import 384 entry
enedis2mqtt    | 2021-12-17 00:37:02.646369 - INFO  : Load 2021-10-28 => 2021-11-04
enedis2mqtt    | 2021-12-17 00:37:02.647262 - INFO  : Data is missing between 2021-10-28 / 2021-11-04
enedis2mqtt    | 2021-12-17 00:37:02.647298 - INFO  :  => Load data from API
enedis2mqtt    | 2021-12-17 00:37:02.647426 - DEBUG : call_number : 11 (max : 15)
enedis2mqtt    | 2021-12-17 00:37:02.652938 - DEBUG : Call API : https://enedisgateway.tech/api
enedis2mqtt    | 2021-12-17 00:37:02.653040 - DEBUG : Data : {"type": "consumption_load_curve", "usage_point_id": "XXX", "start": "2021-10-28", "end": "2021-11-04"}
enedis2mqtt    | 2021-12-17 00:37:02.825173 - INFO  : =====> ERROR : Exception - detailBeetwen <======
enedis2mqtt    | 2021-12-17 00:37:02.825756 - INFO  : Expecting value: line 1 column 1 (char 0)
enedis2mqtt    | Traceback (most recent call last):
enedis2mqtt    |   File "/app/detail.py", line 253, in detailBeetwen
enedis2mqtt    |     detail = f.apiRequest(cur, con, pdl, type="POST", url=f"{url}", headers=headers, data=json.dumps(data))
enedis2mqtt    |   File "/app/function.py", line 145, in apiRequest
enedis2mqtt    |     retour = requests.request(type, url=f"{url}", timeout=240, headers=headers, data=data).json()
enedis2mqtt    |   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 897, in json
enedis2mqtt    |     return complexjson.loads(self.text, **kwargs)
enedis2mqtt    |   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
enedis2mqtt    |     return _default_decoder.decode(s)
enedis2mqtt    |   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
enedis2mqtt    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
enedis2mqtt    |   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
enedis2mqtt    |     raise JSONDecodeError("Expecting value", s, err.value) from None
enedis2mqtt    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
enedis2mqtt    |
enedis2mqtt    | During handling of the above exception, another exception occurred:
enedis2mqtt    |
enedis2mqtt    | Traceback (most recent call last):
enedis2mqtt    |   File "/app/main.py", line 656, in <module>
enedis2mqtt    |     run(pdl, pdl_config)
enedis2mqtt    |   File "/app/main.py", line 328, in run
enedis2mqtt    |     ha_discovery_consumption = detail.getDetail(headers, cur, con, client, pdl, pdl_config, "consumption",
enedis2mqtt    |   File "/app/detail.py", line 59, in getDetail
enedis2mqtt    |     data = detailBeetwen(headers, cur, con, url, pdl, pdl_config, mode, dateBegin, dateEnded, last_activation_date,
enedis2mqtt    |   File "/app/detail.py", line 299, in detailBeetwen
enedis2mqtt    |     for error_key, error_msg in detail.items():
enedis2mqtt    | UnboundLocalError: local variable 'detail' referenced before assignment
```

**Configuration**
```
enedis_gateway:
  'XXX':
    addresses: true
    consumption: true
    consumption_detail: true
    consumption_price_base: 0.10791
    consumption_price_hc: 0
    consumption_price_hp: 0
    offpeak_hours: null
    plan: BASE
    production: false
    production_detail: false
    refresh_addresses: false
    refresh_contract: false
```

**Type d'installation**
Docker

**Version : 0.7.7**

**Comment by m4dm4rtig4n** [comment]
J'ai pas mal de soucis hardware sur le serveur qui host la solution actuellement, probablement que tu as call pendant que celui-ci était HS.
Faudrait juste que je catch un peu mieux les erreurs :/
Tu peut faire un retry stp ?

**Comment by lesensei** [comment]
Effectivement, j'avais laissé tourner le conteneur et il a fini par réussir, c'est tout bon, merci :-) Et bon courage avec ce serveur capricieux !
