### ISSUE TITLE
[HELP] - TypeError: string indices must be integers

### ISSUE THREAD

**Issue by orionevo14** [m4dm4rtig4n/enedisgateway2mqtt#91]
**Description de la fonctionnalité**

L'app crash au démarrage. A fonctionné brièvement et récupéré quelques infos, mais crash aujourd'hui après la màj Home Assistant 2021.12.3 et OS 7.0

Message d'erreur dans les logs :
2021-12-21 18:34:42.472346 - INFO  : Get Consumption :
2021-12-21 18:34:42.546779 - INFO  : Data is missing between 2020-12-21 / 2021-12-21
2021-12-21 18:34:42.546874 - INFO  :  => Load data from API
2021-12-21 18:34:43.203400 - INFO  : =====> ERROR : Exception <======
2021-12-21 18:34:43.203552 - INFO  : 'meter_reading'
2021-12-21 18:34:43.203625 - INFO  : ==> usage_point_id => XXXXXXXXXXX
2021-12-21 18:34:43.203678 - INFO  : ==> error => token_refresh_401
2021-12-21 18:34:43.203728 - INFO  : ==> description => Une erreur est survenue, merci de renouveller vos consentements.
2021-12-21 18:34:43.203787 - INFO  : ==> user_alert => True
Traceback (most recent call last):
  File "/app/main.py", line 656, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 292, in run
    ha_discovery_consumption = day.getDaily(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/daily.py", line 48, in getDaily
    current_value = int(value["value"])
TypeError: string indices must be integers

**Type d'installation**
HassIO 7.0

**Version : 0.7.7**

**Comment by orionevo14** [comment]
Refonctionne sans changement de conf après un reboot...

**Comment by orionevo14** [comment]
Crash systématiquement avec ce message au premier lancement chaque jour, il faut le lancer une deuxième fois pour que ça passe.

**Comment by cvalentin-dkt** [comment]
Essayer de faire step by step :

- Arrêter le conteneur/service
- Passer en derniere version stable si ce n'est pas le cas (0.7.7)
- Supprimer le cache (enedisgateway.db)
- Revérifier le config.yml au niveau du bloc enedis_gateway en vérifiant qu'il y a bien les quotes (")
```
enedis_gateway:
  "XXXXXXXXXXXXXX":
    token: "YOUR_TOKEN"   
```
- Relancer le conteneur/service.

**Comment by orionevo14** [comment]
Hello,
Pas mieux, toujours le crash :
2021-12-25 22:51:15.381354 - INFO  :  => Load data from API
2021-12-25 22:51:18.366104 - INFO  : =====> ERROR : Exception <======
2021-12-25 22:51:18.366560 - INFO  : 'meter_reading'
2021-12-25 22:51:18.366837 - INFO  : ==> usage_point_id => 02423444186347
2021-12-25 22:51:18.367105 - INFO  : ==> error => token_refresh_401
2021-12-25 22:51:18.367336 - INFO  : ==> description => Une erreur est survenue, merci de renouveller vos consentements.
2021-12-25 22:51:18.367563 - INFO  : ==> user_alert => True
Traceback (most recent call last):
  File "/app/main.py", line 656, in <module>
    run(pdl, pdl_config)
  File "/app/main.py", line 292, in run
    ha_discovery_consumption = day.getDaily(headers, cur, con, client, pdl, pdl_config, "consumption",
  File "/app/daily.py", line 48, in getDaily
    current_value = int(value["value"])
TypeError: string indices must be integers
[22:51:18] FATAL: The app has crashed. Are you sure you entered the correct config options?

Fini par se lancer après un autre redémarrage
